[project]
name = "vcsmc"
version = "0.0.1"
description = "Variational Combined Sequential Monte Carlo"
readme = "README.md"
authors = [
    { name="Alex Chen", email="azc2110@columbia.edu" },
    { name="Antonio Moretti", email="am4134@columbia.edu" },
]
requires-python = "~=3.11"
dependencies = [
    "ipykernel",
    "notebook",
    "ipywidgets",
    "torch",
    "torch_tb_profiler",
    "tensorboard",
    "numpy",
    "scipy",
    "matplotlib",
    "tqdm",
    "bio",
    "hyperbolic",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["vcsmc"]

[tool.isort]
profile = "black"
